# p1/Vagrantfile
Vagrant.configure("2") do |config|
  # Base box
  config.vm.box         = "generic/ubuntu2404"
  config.vm.box_version = ">= 4.3.12"

  # Disable automatic SSH key insertion
  config.ssh.insert_key = false

  # Sync folder
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__auto: true

  # VirtualBox provider
  config.vm.provider "virtualbox" do |vb|
    vb.gui     = false
    vb.memory  = 1024
    vb.cpus    = 1
    vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
  end

  # ---------- Server Node ----------
  config.vm.define "alrahmouS" do |m|
    m.vm.hostname = "alrahmouS"
    # Private network for cluster communication
    m.vm.network "private_network", ip: "192.168.56.110"
    m.vm.provision "shell", path: "scripts/setup_server.sh"
  end

  # ---------- Worker Node ----------
  config.vm.define "alrahmouSW" do |m|
    m.vm.hostname = "alrahmouSW"
    # Private network for cluster communication
    m.vm.network "private_network", ip: "192.168.56.111"
    m.vm.provision "shell", path: "scripts/setup_worker.sh"
  end
end
